name: terminal_game_app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: terminal_game_app
  db:
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: terminal_user
      POSTGRES_DB: terminal_game_development
#      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_PASSWORD: terminal_games_are_cool
    volumes:
#      - db_data:/var/lib/postgresql/data | old volume path before 17. this new method allows for upgrading easier
      - db_data:/var/lib/postgresql
#      - db_data:/var/lib/postgresql/data
#    secrets:
#      - db_password

volumes:
    db_data:

#secrets:
#    db_password:
#      file: ./run/secrets/db_password.txt